# Generated by Django 5.2.17 on 2026-08-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
