# Generated by Django 5.2.17 on 2026-10-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0004_message_is_read"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="people.person",
            ),
        ),
    ]
