# Generated by Django 5.2.17 on 2026-10-04 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("friend", "Friend"),
                            ("colleague", "Colleague"),
                            ("manager", "Manager"),
                            ("client", "Client"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "name"], name="people_pers_user_id_3519af_idx"
                    ),
                    models.Index(
                        fields=["user", "phone_number"],
                        name="people_pers_user_id_546000_idx",
                    ),
                    models.Index(
                        fields=["user", "email"], name="people_pers_user_id_aa100d_idx"
                    ),
                    models.Index(
                        fields=["user", "relationship"],
                        name="people_pers_user_id_0a5957_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="people_pers_user_id_3c208d_idx",
                    ),
                ],
            },
        ),
    ]
