# Generated by Django 5.2.17 on 2026-10-02 14:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("preference", "Preference"),
                            ("fact", "Fact"),
                            ("relationship", "Relationship"),
                            ("instruction", "Instruction"),
                            ("goal", "Goal"),
                            ("task", "Task"),
                            ("event", "Event"),
                            ("context", "Context"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="memory_memo_user_id_ca6b36_idx",
                    ),
                    models.Index(
                        fields=["user", "memory_type"],
                        name="memory_memo_user_id_839063_idx",
                    ),
                    models.Index(
                        fields=["user", "expires_at"],
                        name="memory_memo_user_id_896589_idx",
                    ),
                    models.Index(
                        fields=["user", "importance"],
                        name="memory_memo_user_id_d470c4_idx",
                    ),
                ],
            },
        ),
    ]
