# Generated by Django 5.2.17 on 2026-08-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
