# Generated by Django 5.2.17 on 2026-08-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_fix_language_seed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_users",
                to="users.language",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="voice_language_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voice_users",
                to="users.language",
            ),
        ),
    ]
