# Generated by Django 5.2.17 on 2026-08-18 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_backfill_all_user_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="preferred_language",
        ),
        migrations.RemoveField(
            model_name="user",
            name="voice_language",
        ),
    ]
