# Generated by Django 5.2.17 on 2026-09-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_user_preferred_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
