# Generated by Django 5.2.17 on 2026-09-29 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_whatsapp_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="NIRAPersonalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("communication_style", models.JSONField(blank=True, default=dict)),
                ("work_info", models.JSONField(blank=True, default=dict)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("important_people", models.JSONField(blank=True, default=list)),
                ("custom_instructions", models.TextField(blank=True, default="")),
                ("privacy_settings", models.JSONField(blank=True, default=dict)),
                ("memory_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nira_personal_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
